name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Install Playwright browsers
        run: pnpm exec playwright install
      - name: Run Playwright/BDD tests
        run: npm run bdd:full
        env:
          NODE_ENV: test
          AI_FOUNDRY_PROJECT_CONNECTION_STRING: test
          AI_MODEL: gpt-4o
          VITE_PARTYKIT_BASE_URL: wss://partykit.jcreek.partykit.dev
          PARTYKIT_BASE_URL: wss://partykit.jcreek.partykit.dev
